apiVersion: ENC[AES256_GCM,data:SAM=,iv:EqloQcc2DaQDFRpLiWPunWPXDmz/3oVqojbcFruQIeQ=,tag:HxPGUOCcw99/y6XtpNnqIg==,type:str]
kind: ENC[AES256_GCM,data:7lqI3uUg,iv:iVyQlFJaltkN1ENxnZCEKyHRe7ZRb76MDsNqDyk1jQw=,tag:UOqBxgFucculZzbARl1E3g==,type:str]
metadata:
    name: ENC[AES256_GCM,data:HuDqBH38Vaj1qJg=,iv:yfVb9ZUQnBADiMVHuETNACfAVTnCkAFy555TbB38h6A=,tag:QR6zW2Zy96ywmFaJEUf+ow==,type:str]
    namespace: ENC[AES256_GCM,data:uySszcqVzw==,iv:JMGZi1jgyVn3/VUimsZfAtErlXZwBEMnDB5na+3ZMuY=,tag:ati42oj7YqRZel19D9qARw==,type:str]
type: ENC[AES256_GCM,data:SYbxWD+S,iv:K2Zq3qRUsND545v3gDT8w6/6RrsBkxqGT7M6baP6abI=,tag:/0wGjaGzMFZHtY2T+8N9hQ==,type:str]
stringData:
    api-key: ENC[AES256_GCM,data:J6hTL0hZ6G2rrYJehWrUzi/GzQsOJX2/Fm4czQ0=,iv:vLyWr17hv+qYfOrUSFWf9VRBm2vf7KvuvkNgLYiR0Rg=,tag:G++4VUBJYAnAoi8VnMpFRA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpeU95Ym9laFA3WXhnemVR
            UEZyek00RnFkaTFnemZpTG5OSktzbUkwb1NjCklxTjJBNlFUUmN3N0QwRVpIUjRq
            dHY0bzhleU1leXR2c0RGakwyV0FDV0EKLS0tIDBkeU1XcFB3OTFBTXBHQ3orbDUw
            VlA1QXc4ZXZ0TDhWL0J1eXJWNHREeG8K+EHqqkPrBrqQkRmOr2WfMv+pKzDJ0I/G
            fzHjSPM1e0RTlPSszDJoQcWr2xjz7PjrfWa0zyg/7MHfV7rPtrBQjQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xyf9zgm66ala9hf4mwsfmg9m2jvp7q5huvytsvp9qtg375eg9yuqqjqpc3
    lastmodified: "2026-09-16T15:05:22Z"
    mac: ENC[AES256_GCM,data:wfh65iuZZkS698Ei/3MtQ/8vxAs7oK7FhRM5vgJTn0ku9qa8KN4bxPXNYem4v790TNXXRZuTrndOUO5iGx1l9H+GV46Ljuhst4EjCQH0iaFV7JibLMUqS2oFel2I5ml8wFeFj1HvSNxzJATbrzMrgrWmWwAjsNmig6V2ov5T3a0=,iv:3pXBj+7ja86A/PzbFpBwCOLlk6N+pU4Uj138n47u030=,tag:1i5cuntWtfizSgaz58ZKfQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
